version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: pg-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: main


